version: build{build}

skip_commits:
  files:
    - .travis.yml

cache:
- x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z

environment:
  matrix:
  - MINGW_DIR: mingw64
    MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z/download
    MINGW_ARCHIVE: x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
    WITH_FTDI: ON
    FORCE_FTDI: ON
    VERBOSE: 1

clone_folder: c:\dev\pulp-bridge
clone_depth: 5

install:
  - if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  - cd
  - appveyor DownloadFile http://jaist.dl.sourceforge.net/project/libusb-win32/libusb-win32-releases/1.2.6.0/libusb-win32-bin-1.2.6.0.zip
  - 7z x libusb-win32-bin-1.2.6.0.zip
  - dir libusb-win32-bin-1.2.6.0
  - dir libusb-win32-bin-1.2.6.0\include
  - move libusb-win32-bin-1.2.6.0\bin\x86\libusb0_x86.dll libusb0.dll
  - dir
before_build:
  - set Path=%CD%\%MINGW_DIR%\bin;%Path%
  - git config --global core.autocrlf input
  - g++ --version
  - mingw32-make --version
  - cmake --version
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%

  - cd c:\dev\pulp-bridge
  - md build

build_script:
  - cd build
  - cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DStandaloneApp=YES  -DCMAKE_INSTALL_PREFIX="c:/dev/pulp-bridge/install" -DWithFTDI=$WITH_FTDI -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
  - cmake --build . --target install -- VERBOSE=1

test: off
