version: build{build}

skip_commits:
  files:
    - .travis.yml

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

clone_folder: c:\dev\pulp-bridge
clone_depth: 5

install:
  - SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"
  - bash -lc "pacman -S --needed --noconfirm pacman-mirrors"
  - bash -lc "pacman -S --needed --noconfirm git"
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain cmake libtool make patch mingw-w64-x86_64-libtool"

before_build:
  - cd c:\dev\pulp-bridge
  - md build
  - bash -lc "g++ --version"
  - bash -lc "make --version"
  - bash -lc "cmake --version"
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
# -DCMAKE_IGNORE_PATH=\"C:/Program Files/Git/usr/bin\"
build_script:
  - cd build
  - bash -lc "cmake .. -G \"MinGW Makefiles\" -DCMAKE_BUILD_TYPE=Debug -DStandaloneApp=YES  -DCMAKE_INSTALL_PREFIX=\"c:/dev/pulp-bridge/install\" -DForceFTDI=$FORCE_FTDI -DWithFTDI=$WITH_FTDI"
  - bash -lc "make all install VERBOSE=1"

on_failure:
  - type "C:\dev\pulp-bridge\build\json-tools\src\json-tools-stamp\json-tools-download-*.log"

test: off
